auth:
  jwtSecret: JWT_SECRET
  discordClientId: AUTH_DISCORD_CLIENT_ID
  discordClientSecret: AUTH_DISCORD_CLIENT_SECRET
  discordCallbackUrl: AUTH_DISCORD_CALLBACK_URL
  discordRppCallbackUrl: AUTH_DISCORD_RPP_CALLBACK_URL
