server:
  port: 8111
  frontendRoot: '_FRONTENDROOT_'
  newsRoot: 'http://localhost:8081'
  maxUploadSpacePerUserMiB: 200
  stewardWebhookPort: 8112
  stewardWebhookUrl: 'http://steward:8112'

db:
  type: 'mariadb'
  host: 'mariadb'
  port: 3306
  database: 'lightarchives'
  username: 'mariadb'
  password: 'mariadb'
  synchronize: true
  logging: true

redis:
  host: 'redis'
  port: 6379

mail:
  host: '_SMTPHOST_'
  port: _SMTPPORT_
  secure: true
  username: _SMTPUSER_
  password: _SMPTPASSWORD_
  from: '_SMTPFROM_'

auth:
  jwtSecret: 'secret'
  jwtExpiry: '30d'
  scopedJwtExpiry: '365d'

s3:
  endpoint: 'https://servername.tld'
  bucketName: 'mybucket'
  publicRootUrl: 'https://publicservername.tld'
  accessKeyId: 'MY_ACCESS_KEY'
  secretAccessKey: 'MY_SECRET_ACCESS_KEY'

discord:
  botToken: 'INSERT_TOKEN_HERE'
  serverId: 'INSERT_ID_HERE'
  announcementChannel: 'INSERT_ID_HERE'
  noticeboardChannel: 'INSERT_ID_HERE'
